okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-htw138ror3btjs0l.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: https://api-endpoint.com